// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjho-gvAp8eW-YgNhsVxR4Qx5Wfq08G1M',
    appId: '1:969719431290:web:becfcd1b2131105629bbc3',
    messagingSenderId: '969719431290',
    projectId: 'project-flutter-790d1',
    authDomain: 'project-flutter-790d1.firebaseapp.com',
    storageBucket: 'project-flutter-790d1.firebasestorage.app',
    measurementId: 'G-GR6KNMHH2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSn-H3Z5ZK5-cqfERK0ndOmDGrtmj-6Y',
    appId: '1:969719431290:android:ed969cad69ebfd3029bbc3',
    messagingSenderId: '969719431290',
    projectId: 'project-flutter-790d1',
    storageBucket: 'project-flutter-790d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKpdoupO-pIMBRln-X7ZCNLljDQiHVdU',
    appId: '1:969719431290:ios:859ad373e9a6b7f529bbc3',
    messagingSenderId: '969719431290',
    projectId: 'project-flutter-790d1',
    storageBucket: 'project-flutter-790d1.firebasestorage.app',
    iosClientId: '969719431290-anqu6nt7blf4k3halb2n0gqsvc9bjcla.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnKpdoupO-pIMBRln-X7ZCNLljDQiHVdU',
    appId: '1:969719431290:ios:859ad373e9a6b7f529bbc3',
    messagingSenderId: '969719431290',
    projectId: 'project-flutter-790d1',
    storageBucket: 'project-flutter-790d1.firebasestorage.app',
    iosClientId: '969719431290-anqu6nt7blf4k3halb2n0gqsvc9bjcla.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjho-gvAp8eW-YgNhsVxR4Qx5Wfq08G1M',
    appId: '1:969719431290:web:e16e3c2fc5d34cc729bbc3',
    messagingSenderId: '969719431290',
    projectId: 'project-flutter-790d1',
    authDomain: 'project-flutter-790d1.firebaseapp.com',
    storageBucket: 'project-flutter-790d1.firebasestorage.app',
    measurementId: 'G-4SDLNT622K',
  );
}
